name: coachmaster
description: "Professional sports team management application for coaches to manage players, training sessions, matches, and team statistics."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.1
  # Keeping Hive temporarily for migration
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Firebase dependencies
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_analytics: ^12.0.1
  connectivity_plus: ^7.0.0
  google_sign_in: ^6.2.1
  # Image handling dependencies
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  image: ^4.2.0
  path_provider: ^2.1.3
  path: ^1.9.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - docs/logo_coach_master.png
    - docs/logo_coachmaster.png
    - docs/favicon.ico

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "docs/logo_coach_master.png"
    background_color: "#000000"
    theme_color: "#FFA700"
  windows:
    generate: true
    image_path: "docs/logo_coach_master.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "docs/logo_coach_master.png"
  image_path: "docs/logo_coach_master.png"
