// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBl1fKsBByRfO5JwJIOmeyzkJ6dSRpJvo',
    appId: '1:25162710455:web:2428e331c631ca7ce6fc32',
    messagingSenderId: '25162710455',
    projectId: 'coach-mast-3r',
    authDomain: 'coach-mast-3r.firebaseapp.com',
    storageBucket: 'coach-mast-3r.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslf_axzlT_SvyjvppKjAgwZLAXGOYbL0',
    appId: '1:25162710455:android:3e8a2777165e26dde6fc32',
    messagingSenderId: '25162710455',
    projectId: 'coach-mast-3r',
    storageBucket: 'coach-mast-3r.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjjz-VmD3qMaomfiixu0c_x5vcuf5FrYs',
    appId: '1:25162710455:ios:a8dc0563adb70426e6fc32',
    messagingSenderId: '25162710455',
    projectId: 'coach-mast-3r',
    storageBucket: 'coach-mast-3r.firebasestorage.app',
    iosBundleId: 'com.example.musify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjjz-VmD3qMaomfiixu0c_x5vcuf5FrYs',
    appId: '1:25162710455:ios:a8dc0563adb70426e6fc32',
    messagingSenderId: '25162710455',
    projectId: 'coach-mast-3r',
    storageBucket: 'coach-mast-3r.firebasestorage.app',
    iosBundleId: 'com.example.musify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBl1fKsBByRfO5JwJIOmeyzkJ6dSRpJvo',
    appId: '1:25162710455:web:59b6ed6aaec7b0a8e6fc32',
    messagingSenderId: '25162710455',
    projectId: 'coach-mast-3r',
    authDomain: 'coach-mast-3r.firebaseapp.com',
    storageBucket: 'coach-mast-3r.firebasestorage.app',
  );

}