name: Notify Translators

on:
  push:
    branches:
      - master
    paths:
      - 'lib/localization/app_en.arb'
    tags-ignore:
      - '*'

jobs:
  notify-translators:
    runs-on: ubuntu-latest

    steps:
    - name: Check Repository
      run: |
        if [ "${{ github.repository }}" != "gokadzev/Musify" ]; then
          echo "Skipping workflow run as it's not the original repository."
          exit 0
        fi

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Load Translator Info
      id: load_translators
      run: |
        if [ ! -f translators.json ]; then
          echo "translators.json file is missing, exiting."
          exit 1
        fi
        cp translators.json /tmp/translators.json

    - name: Notify All Translators
      run: |
        # Retrieve all translators from the JSON file
        TRANSLATORS=$(jq -r 'to_entries | map("@" + .value) | join(", ")' /tmp/translators.json)

        # Formulate the notification message
        MESSAGE="The main translation file (app_en.arb) has been updated. Please review and update your translations accordingly.\n${TRANSLATORS}"

        # Post a single comment on the commit
        response=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\": \"${MESSAGE}\"}" \
          https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments)

        # Check if the notification was sent successfully
        if [[ "$response" == *"created_at"* ]]; then
          echo "Notification sent successfully."
        else
          echo "Failed to send notification. Response: $response"
        fi
